# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.FloatField(default=0, max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
